name: Daily Job

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight UTC every day

jobs:
  run-daily-job:
    runs-on: ubuntu-latest

    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}  
      KASSAL_BEARER: ${{ secrets.KASSAL_BEARER }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run JavaScript
        run: .js
